dependencies {
    api("com.ruling_0:MaterialLib:0.10.0-mu:dev")
    implementation("com.github.GTNewHorizons:GTNHLib:0.11.31:dev")
    implementation('com.github.GTNewHorizons:GT5-Unofficial:5.99.99-mu5:dev')
    implementation('com.github.GTNewHorizons:VisualProspecting:1.5.38-mu:dev')

    runtimeOnlyNonPublishable('com.github.GTNewHorizons:Angelica:2.1.56:dev') { transitive = false }

    runtimeOnlyNonPublishable(rfg.deobf('maven.modrinth:journeymap:5.2.20')) { transitive = false }
}
